// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA4ed21i8rSzRsBe18X1LF0lNpxfx-BsI',
    appId: '1:571460887304:web:bd70e4130b94a8c26442bd',
    messagingSenderId: '571460887304',
    projectId: 'estudy-376aa',
    authDomain: 'estudy-376aa.firebaseapp.com',
    databaseURL: 'https://estudy-376aa-default-rtdb.firebaseio.com',
    storageBucket: 'estudy-376aa.appspot.com',
    measurementId: 'G-RRWYF95QE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL1ZPilaiDtYJJpShOdqbQm26Q2rwin-M',
    appId: '1:571460887304:android:968e4302e2ed62756442bd',
    messagingSenderId: '571460887304',
    projectId: 'estudy-376aa',
    databaseURL: 'https://estudy-376aa-default-rtdb.firebaseio.com',
    storageBucket: 'estudy-376aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLSeuHCkrzEWOOYaziHSOg-bnrx64PIKc',
    appId: '1:571460887304:ios:8479313f75e5ba9e6442bd',
    messagingSenderId: '571460887304',
    projectId: 'estudy-376aa',
    databaseURL: 'https://estudy-376aa-default-rtdb.firebaseio.com',
    storageBucket: 'estudy-376aa.appspot.com',
    iosClientId: '571460887304-33mcr95sso5n2jjfje5i93gtm639odq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLSeuHCkrzEWOOYaziHSOg-bnrx64PIKc',
    appId: '1:571460887304:ios:8479313f75e5ba9e6442bd',
    messagingSenderId: '571460887304',
    projectId: 'estudy-376aa',
    databaseURL: 'https://estudy-376aa-default-rtdb.firebaseio.com',
    storageBucket: 'estudy-376aa.appspot.com',
    iosClientId: '571460887304-33mcr95sso5n2jjfje5i93gtm639odq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );
}
